import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <header className="header_background">
              <nav className="header_nav">
                  <ul className="header_navlinks wrap">
                      <li>
                          <a href="#home" className="s1-link">Home</a>
                      </li>
                      <li>
                          <a href="#about" className="s1-link">About me</a>
                      </li>
                      <li>
                          <a href="#skills" className="s1-link">Skills</a>
                      </li>
                      <li>
                          <a href="#port" className="s1-link">Portfolio</a>
                      </li>
                      <li>
                          <a href="#contacts" className="s1-link kek">Cotnacts</a>
                      </li>
                  </ul>
                  <div className="header_nav_close">
                      <div className="header_nav_close_stripe">
                      </div>
                  </div>
                  {/* <!--изменение--> */}
                  <div className="lang_choice_main_mobile">
                      <span>
                          <a href="#!" className="lang_choice ru">ru</a> <span className="lang_choice ru">|</span> <a href="#!" className="lang_choice eng">eng</a>
                      </span>
                  </div>
              </nav>
          </header>
            <main>
              <div className="burger_menu">
                  <div className="burger_menu_stripe">
                  </div>
              </div>
              <section className="section_wrap wrap section" id="home">
                  <h1 className="header_title">Denis Novik</h1>
                  <div className="header_subtitle">UX | UI designer 24 years old, Minsk</div>
                  <div className="lang_choice_main">
                      <span>
                          <a href="" className="lang_choice ru">ru</a> <span className="lang_choice ru">|</span> <a href="" className="lang_choice eng">eng</a>
                      </span>
                  </div>
                  <div className="header_pic">
                      <img className="header_picture" src="../huy/img/header_pic.jpg" alt="" />
                  </div>
              </section>
              <section className="about section" id="about">
                  <h3 className="about_title">About me</h3>
                  <p className="about_article">Hi, I&rsquo;m Denis – UX/UI designer from Minsk.
                      I&rsquo;m interested in design and everything connected with it. <br />
                      <br /><br />
                      I&rsquo;m studying at courses &rdquo;Web and mobile design
                      interfaces&rdquo; in IT-Academy.<br />
                      <br /><br />
                      Ready to implement excellent projects
                      with wonderful people.</p>
              </section>
              <section className="skills wrap section" id="skills">
                  <h3 className="skills_title">Skills</h3>
                  <p className="skills_subtitle">I work in such programs as</p>
                  <div className="skills_grid">
                      <div className="ps cell">
                          <img className="skill_pic" src="../huy/img/ps.jpg" alt="AdobePhotoshop" />
                          <p className="describe">Adobe Photoshop</p>
                          <img src="../huy/img/most_stars.svg" alt="" className="skills_score" />
                      </div>
                      <div className="ai cell">
                          <img className="skill_pic" src="../huy/img/ai.png" alt="AdobeIllustrator" />
                          <p className="describe">Adobe Illustrator</p>
                          <img src="../huy/img/ai_stars.svg" alt="" className="skills_score" />
                      </div>
                      <div className="ae cell">
                          <img className="skill_pic" src="../huy/img/ae.png" alt="AfterEffects" />
                          <p className="describe">Adobe After Effects</p>
                          <img src="../huy/img/most_stars.svg" alt="" className="skills_score" />
                      </div>
                      <div className="figma cell">
                          <img className="skill_pic_f" src="../huy/img/figma.jpg" alt="figma" />
                          <p className="describe">Figma</p>
                          <img src="../huy/img/most_stars.svg" alt="" className="skills_score_f" />
                      </div>
                  </div>
              </section>
              <section className="portfolio">
                  <div className="wrap">
                      <h3 className="portfolio_title section" id="port">Portfolio</h3>
                  </div>
                    <figure className="example_pic">
                        <img src="../huy/img/woman.jpg" alt="" className="portfolio_pic" />
                        <figcaption>Online fashion store - Homepage</figcaption>
                    </figure>
                    <figure className="example_pic">
                        <img src="../huy/img/reebok.jpg" alt="" className="portfolio_pic" />
                        <figcaption>Landing Page - Concept</figcaption>
                    </figure>
                    <figure className="example_pic">
                        <img src="../huy/img/braun.jpg" alt="" className="portfolio_pic" />
                            <figcaption>Reebok Store - Concept</figcaption>
                    </figure>
             </section>
             <section className="contacts wrap section" id="contacts">
                <h3 className="contacts_title">Contacts</h3>
                <p className="contacts_subtitle">Want to know more or just chat? You are welcome!</p>
                <button className="contacts_btn" type="submit">Send massege</button>
            </section> 
        </main>
        <footer className="wrap">
        <div className="footer_grid">
        <div className="social_media">
            <a href="!#"><img src="../huy/img/linkedin.svg" alt="" className="sm_anim" /></a>
            <a href="!#"><img src="../huy/img/instagramm.svg" alt="" className="sm_anim" /></a>
            <a href="!#"><img src="../huy/img/behance.svg" alt="" className="sm_anim" /></a>
            <a href="!#"><img src="../huy/img/dribble.svg" alt="" className="sm_anim" /></a>
        </div>
        </div>
        <p className="footer_describe">
            Like me on LinkedIn, Instagram, Behance, Dribble
        </p>
    </footer>
      {/* <main classNameName={styles.main}>
        <div classNameName={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code classNameName={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                classNameName={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div classNameName={styles.center}>
          <Image
            classNameName={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div classNameName={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div classNameName={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 classNameName={inter.classNameName}>
              Docs <span>-&gt;</span>
            </h2>
            <p classNameName={inter.classNameName}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 classNameName={inter.classNameName}>
              Learn <span>-&gt;</span>
            </h2>
            <p classNameName={inter.classNameName}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 classNameName={inter.classNameName}>
              Templates <span>-&gt;</span>
            </h2>
            <p classNameName={inter.classNameName}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 classNameName={inter.classNameName}>
              Deploy <span>-&gt;</span>
            </h2>
            <p classNameName={inter.classNameName}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  )
}
